In [2]:
import numpy as np
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)

[[3400 6200]
 [ 374  712]]


In [3]:
# The dot product is calculated as:

# [100 * 10 + 200 * 12, 100 * 20 + 200 * 21] [23*10+12*12, 23*20 + 12*21] 

In [4]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)  

5528


In [5]:
# np.vdot(a,b) = 100 *10 + 200 * 20 + 23 * 12 + 12 * 21 = 5528

In [6]:
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  

130


# multiplication of matrix

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [11]:
# element wise multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b

array([ 4, 10, 18])

# finding the determinent of the matrix

In [9]:
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


In [10]:
import numpy as np

A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [12]:
# dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

In [13]:
# cross product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.cross(a, b)

array([-3,  6, -3])

In [14]:
import numpy as np  
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
